### ISSUE TITLE
Roadmap for further development

### ISSUE THREAD

**Issue by catfoolyou** [catfoolyou/Eaglercraft-1.12#14]
## Desktop client
- [x]  Eagler authsystem GUIs via implementation of a new GUI for skin selection and authentication by calling it from the place where the mainmenu GUI is normally called, then dropping the player into the menu after username and skin are set.
- [x] Implementing EPK support and utils for working with EPK files (probably not, see [#20](https://github.com/catfoolyou/Eaglercraft-1.12-Desktop-Runtime/pull/20))
- [x] Rewrite LAN network code to connect through LAN. 
LAN has been removed due to lack of compatibility with EaglercraftX. The dedicated server should be used instead.
- [ ] Implementing websocket connections, using Lax1dude's 1.8 code from `server`, `socket` and `sp`

## Potential web client
- [ ] Reimplementation of all of LWJGL, Google and Apache libraries for web compilation. Might use Lax's codebase for this.

**Comment by catfoolyou** [comment]
See the new web dev issue
