### ISSUE TITLE
Web port roadmap

### ISSUE THREAD

**Issue by catfoolyou** [catfoolyou/Eaglercraft-1.12#25]
Basically a place to write shit I need to fix as I go

So far I need Eagler's GLAllocation because the one I got screwed up a LOT of shit

**Comment by catfoolyou** [comment]
Also a proper roadmap over here:
- [ ] Fully integrate Lax's code and fix all errors
- [ ] Remove native Java libs and reuse Lax's rewritten libs modifying as needed (get guava and commons src)
This shit [here](https://guava.dev/releases/21.0/api/docs/src-html/com/google/common/cache/LoadingCache.html) but replace the last part with the class name. Idk about apache, maybe [this](https://github.com/apache/commons-lang)?
- [ ] Finally rewrite a ton of shit so it works with TeaVM (see [this](https://teavm.org/jcl-report/recent/jcl.html)) (Also I am a dumbass and this is definitely the hardest part)
